#ifndef CINDER_STATUS_H_
#define CINDER_STATUS_H_

typedef enum
{
    CINDER_STATUS_OK,
    CINDER_STATUS_SUBSYSTEM_INIT_FAILED,
    CINDER_STATUS_WINDOW_CREATE_FAILED,
    CINDER_STATUS_RENDERER_CREATE_FAILED,
    CINDER_STATUS_PLUGIN_MAX_REACHED,
    CINDER_STATUS_PLUGIN_NO_NAME,
    CINDER_STATUS_PLUGIN_DUPLICATE_NAME,
    CINDER_STATUS_RENDERER_MISSING,
    CINDER_STATUS_TEXTURE_NULL,

} CinderStatus;

#endif /* CINDER_STATUS_H_ */