#ifndef CINDER_ERROR_H_
#define CINDER_ERROR_H_

#include <stdbool.h>

/**
 * @brief Severity levels for Cinder log messages.
 *
 * Passed to the log callback to indicate the severity of a message.
 * CINDER_LOG_NONE is a sentinel value used internally to indicate
 * that no message has been logged yet.
 *
 * @see CinderSetErrorCallback(), CinderErrorCallback
 */
typedef enum
{
    CINDER_LOG_NONE,    /**< No level — used internally as a sentinel, not a real log level. */
    CINDER_LOG_INFO,    /**< Informational message — normal operation. */
    CINDER_LOG_WARNING, /**< Warning — something unexpected happened but execution can continue. */
    CINDER_LOG_ERROR,   /**< Error — an operation failed. */

} CinderLogLevel;

/**
 * @brief Callback type for receiving Cinder log and error messages.
 *
 * Set a callback with CinderSetErrorCallback() to receive all log
 * messages generated by Cinder. The callback is invoked for every
 * message at any log level, including INFO, WARNING, and ERROR.
 *
 * @param level    Severity level of the message.
 * @param message  Null-terminated string containing the log message.
 * @param file     Source file where the message was generated.
 * @param function Function name where the message was generated.
 * @param line     Line number where the message was generated.
 * @param userdata User-provided pointer passed through from CinderSetErrorCallback().
 *
 * @see CinderSetErrorCallback(), CinderLogLevel
 */
typedef void (*CinderErrorCallback)(
    CinderLogLevel level,
    const char *message,
    const char *file,
    const char *function,
    int line,
    void *userdata);

/**
 * @brief Sets the log callback invoked for every Cinder log message.
 *
 * Replaces the current callback with @p cb. Pass NULL to disable
 * logging entirely. The default callback (CinderDefaultLogCallback)
 * is installed automatically by CinderInit() if no callback is set.
 *
 * @param cb       Callback to invoke on each log message, or NULL to disable.
 * @param userdata User-provided pointer passed through to the callback unchanged.
 *
 * @see CinderErrorCallback, CinderDefaultLogCallback
 */
void CinderSetErrorCallback(CinderErrorCallback cb, void *userdata);

/**
 * @brief Returns the most recent error message.
 *
 * Returns the message string from the last log call at any level.
 * Returns NULL if no message has been logged or after CinderClearError().
 *
 * @return Null-terminated error string, or NULL if no error is set.
 *
 * @see CinderClearError(), CinderHasError()
 */
const char *CinderGetError(void);

/**
 * @brief Clears the last error message and log level.
 *
 * Resets the stored error string to NULL and the log level to
 * CINDER_LOG_NONE. Call this after handling an error to reset state.
 *
 * @see CinderGetError(), CinderHasError()
 */
void CinderClearError(void);

/**
 * @brief Returns the severity level of the most recent log message.
 *
 * @return The CinderLogLevel of the last logged message, or
 *         CINDER_LOG_NONE if nothing has been logged yet.
 *
 * @see CinderGetError(), CinderClearError()
 */
CinderLogLevel CinderGetLastLevel(void);

/**
 * @brief Returns whether the last log message was an error.
 *
 * Convenience function equivalent to checking
 * CinderGetLastLevel() == CINDER_LOG_ERROR.
 *
 * @return True if the last logged message was at ERROR level.
 *
 * @see CinderGetLastLevel(), CinderClearError()
 */
bool CinderHasError(void);

/**
 * @brief Internal logging function — do not call directly.
 *
 * Updates the stored error state and invokes the log callback.
 * Use the CINDER_LOG macro instead of calling this function directly.
 *
 * @param level    Severity level of the message.
 * @param msg      Log message string.
 * @param file     Source file where the log was triggered.
 * @param function Function name where the log was triggered.
 * @param line     Line number where the log was triggered.
 *
 * @see CINDER_LOG
 */
void CinderLogInternal__(CinderLogLevel level, const char *msg, const char *file, const char *function, int line);

/**
 * @brief Default log callback that prints messages to stdout or stderr.
 *
 * Installed automatically by CinderInit(). Prints colored, formatted
 * log messages to stderr for WARNING and ERROR, and stdout for INFO.
 * The output format is:
 * @code
 * [LEVEL] file:line (function): message
 * @endcode
 *
 * @param level    Severity level of the message.
 * @param message  Log message string.
 * @param file     Source file where the log was triggered.
 * @param function Function name where the log was triggered.
 * @param line     Line number where the log was triggered.
 * @param userdata Unused — present to satisfy the CinderErrorCallback signature.
 *
 * @see CinderSetErrorCallback(), CinderErrorCallback
 */
void CinderDefaultLogCallback(CinderLogLevel level, const char *message, const char *file, const char *function, int line, void *userdata);

/**
 * @brief Logs a message at the given severity level.
 *
 * Invokes CinderLogInternal__() with the current file, function, and
 * line number automatically injected. This is the preferred way to
 * emit log messages from within Cinder's internals.
 *
 * @param level Severity level — one of the CinderLogLevel values.
 * @param msg   Null-terminated string containing the message to log.
 *
 * @code
 * CINDER_LOG(CINDER_LOG_ERROR, "Failed to create window");
 * @endcode
 *
 * @see CinderLogInternal__(), CinderLogLevel
 */
#define CINDER_LOG(level, msg) CinderLogInternal__((level), (msg), __FILE__, __func__, __LINE__)

#endif /* CINDER_ERROR_H_ */