#ifndef CINDER_STATUS_H_
#define CINDER_STATUS_H_

typedef enum
{
    CINDER_STATUS_OK,
    CINDER_STATUS_SUBSYSTEM_INIT_FAILED,
    CINDER_STATUS_WINDOW_CREATE_FAILED,
    CINDER_STATUS_RENDERER_CREATE_FAILED,

} CinderStatus;

#endif /* CINDER_STATUS_H_ */