#ifndef KITRA_ERROR_H_
#define KITRA_ERROR_H_

#include <stdbool.h>

/**
 * @brief Severity levels for Kitra log messages.
 *
 * Passed to the log callback to indicate the severity of a message.
 * KITRA_LOG_NONE is a sentinel value used internally to indicate
 * that no message has been logged yet.
 *
 * @see KitraSetErrorCallback(), KitraErrorCallback
 */
typedef enum
{
    KITRA_LOG_NONE,    /**< No level — used internally as a sentinel, not a real log level. */
    KITRA_LOG_INFO,    /**< Informational message — normal operation. */
    KITRA_LOG_WARNING, /**< Warning — something unexpected happened but execution can continue. */
    KITRA_LOG_ERROR,   /**< Error — an operation failed. */

} KitraLogLevel;

/**
 * @brief Callback type for receiving Kitra log and error messages.
 *
 * Set a callback with KitraSetErrorCallback() to receive all log
 * messages generated by Kitra. The callback is invoked for every
 * message at any log level, including INFO, WARNING, and ERROR.
 *
 * @param level    Severity level of the message.
 * @param message  Null-terminated string containing the log message.
 * @param file     Source file where the message was generated.
 * @param function Function name where the message was generated.
 * @param line     Line number where the message was generated.
 * @param userdata User-provided pointer passed through from KitraSetErrorCallback().
 *
 * @see KitraSetErrorCallback(), KitraLogLevel
 */
typedef void (*KitraErrorCallback)(
    KitraLogLevel level,
    const char *message,
    const char *file,
    const char *function,
    int line,
    void *userdata);

/**
 * @brief Sets the log callback invoked for every Kitra log message.
 *
 * Replaces the current callback with @p cb. Pass NULL to disable
 * logging entirely. The default callback (KitraDefaultLogCallback)
 * is installed automatically by KitraInit() if no callback is set.
 *
 * @param cb       Callback to invoke on each log message, or NULL to disable.
 * @param userdata User-provided pointer passed through to the callback unchanged.
 *
 * @see KitraErrorCallback, KitraDefaultLogCallback
 */
void KitraSetErrorCallback(KitraErrorCallback cb, void *userdata);

/**
 * @brief Returns the most recent error message.
 *
 * Returns the message string from the last log call at any level.
 * Returns NULL if no message has been logged or after KitraClearError().
 *
 * @return Null-terminated error string, or NULL if no error is set.
 *
 * @see KitraClearError(), KitraHasError()
 */
const char *KitraGetError(void);

/**
 * @brief Clears the last error message and log level.
 *
 * Resets the stored error string to NULL and the log level to
 * KITRA_LOG_NONE. Call this after handling an error to reset state.
 *
 * @see KitraGetError(), KitraHasError()
 */
void KitraClearError(void);

/**
 * @brief Returns the severity level of the most recent log message.
 *
 * @return The KitraLogLevel of the last logged message, or
 *         KITRA_LOG_NONE if nothing has been logged yet.
 *
 * @see KitraGetError(), KitraClearError()
 */
KitraLogLevel KitraGetLastLevel(void);

/**
 * @brief Returns whether the last log message was an error.
 *
 * Convenience function equivalent to checking
 * KitraGetLastLevel() == KITRA_LOG_ERROR.
 *
 * @return True if the last logged message was at ERROR level.
 *
 * @see KitraGetLastLevel(), KitraClearError()
 */
bool KitraHasError(void);

/**
 * @brief Internal logging function — do not call directly.
 *
 * Updates the stored error state and invokes the log callback.
 * Use the KITRA_LOG macro instead of calling this function directly.
 *
 * @param level    Severity level of the message.
 * @param msg      Log message string.
 * @param file     Source file where the log was triggered.
 * @param function Function name where the log was triggered.
 * @param line     Line number where the log was triggered.
 *
 * @see KITRA_LOG
 */
void KitraLogInternal__(KitraLogLevel level, const char *msg, const char *file, const char *function, int line);

/**
 * @brief Default log callback that prints messages to stdout or stderr.
 *
 * Installed automatically by KitraInit(). Prints colored, formatted
 * log messages to stderr for WARNING and ERROR, and stdout for INFO.
 * The output format is:
 * @code
 * [LEVEL] file:line (function): message
 * @endcode
 *
 * @param level    Severity level of the message.
 * @param message  Log message string.
 * @param file     Source file where the log was triggered.
 * @param function Function name where the log was triggered.
 * @param line     Line number where the log was triggered.
 * @param userdata Unused — present to satisfy the KitraErrorCallback signature.
 *
 * @see KitraSetErrorCallback(), KitraErrorCallback
 */
void KitraDefaultLogCallback(KitraLogLevel level, const char *message, const char *file, const char *function, int line, void *userdata);

/**
 * @brief Logs a message at the given severity level.
 *
 * Invokes KitraLogInternal__() with the current file, function, and
 * line number automatically injected. This is the preferred way to
 * emit log messages from within Kitra's internals.
 *
 * @param level Severity level — one of the KitraLogLevel values.
 * @param msg   Null-terminated string containing the message to log.
 *
 * @code
 * KITRA_LOG(KITRA_LOG_ERROR, "Failed to create window");
 * @endcode
 *
 * @see KitraLogInternal__(), KitraLogLevel
 */
#define KITRA_LOG(level, msg) KitraLogInternal__((level), (msg), __FILE__, __func__, __LINE__)

#endif /* KITRA_ERROR_H_ */